# Generated by Django 5.1.5 on 2025-01-25 23:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "num_of_rows",
                    models.SmallIntegerField(
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(9),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "num_of_cols",
                    models.SmallIntegerField(
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(9),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "num_of_mines",
                    models.SmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("board", models.JSONField(default=[])),
                (
                    "remaining_mines",
                    models.SmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(667),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_saved", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
