# Generated by Django 5.1.5 on 2025-01-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=15,
            ),
        ),
    ]
