# Generated by Django 5.1.5 on 2025-01-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_game_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="board",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[("running", "Running"), ("won", "Won"), ("lost", "Lost")],
                default="running",
                max_length=12,
            ),
        ),
    ]
