# Generated by Django 5.1.5 on 2025-01-26 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_game_board_alter_game_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="remaining_mines",
        ),
        migrations.AlterField(
            model_name="game",
            name="num_of_cols",
            field=models.SmallIntegerField(
                default=9,
                validators=[
                    django.core.validators.MinValueValidator(9),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="num_of_mines",
            field=models.SmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="num_of_rows",
            field=models.SmallIntegerField(
                default=9,
                validators=[
                    django.core.validators.MinValueValidator(9),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
    ]
