# Generated by Django 5.1.5 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_game_remaining_mines_alter_game_num_of_cols_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[("RUNNING", "Running"), ("WON", "Won"), ("LOST", "Lost")],
                default="RUNNING",
                max_length=12,
            ),
        ),
    ]
